if (Posts.find().count() === 0) {
  Posts.insert({
      category: '',
      subCategory: '',
      title: '仁威廟',
      startTime: '',
      endTime: '',
      address: '广州市西關泮塘路仁威庙前街20号',
      district: '西關泮塘',
      city: '廣州市',
      xBaidu: '113.242597',
      yBaidu: '23.128864',
      introduction: '始建于宋朝皇祐四年（1052年）时称北帝庙，后来改称仁威庙。历经多次修复、重建，其中明朝天启二年（1622年）、清朝乾隆、同治年间均进行大规模的重修。现存主体建筑坐北朝南，东西阔40米，南北深54至60米，占地2200平方米。沿中轴线前后为头门、正殿、中殿、后殿和后楼；左右为东、西序。中共建政後的1963年左右，當局安排昌華塑料廠在此生產。文化大革命期間，紅衛兵按照當局「破四舊」的意思把廟裡的神像全部打爛，頭門和正殿成為昌華塑料廠車間，東西配殿成為某校辦工廠的工場。1983年8月，仁威庙被公布为广州市文物保护单位。廟宇被佔用期間，工廠在廟內亂搭建，使柱子、樑架等受到嚴重破壞，有的柱子已經傾斜，部分樑架已腐朽；正殿與拜亭的簷已經倒塌，需用架子支撐，搖搖欲墜；樑架的木雕被損壞，有的工藝雕構件已脫落。1993年底塑料厂迁出。近年政府对庙宇进行了较大的扩建和维修，庙前修建大型的仁威庙广场。每年的农历二月初八是仁威庙诞。',
      photo: '',
      video: 'https://youtu.be/HqftvfPp59A',
      sound: '',
      owner: '',
      deleted: 'F',
      createUser: '',
      editUser: '',
      createDateTime: '',
      editDateTime: ''
  });

  Posts.insert({
      category: '',
      subCategory: '',
      title: '佛山祖廟',
      startTime: '',
      endTime: '',
      address: '佛山市禅城区祖庙路21号佛山市博物馆内',
      district: '禅城区',
      city: '佛山市',
      xBaidu: '113.242597',
      yBaidu: '23.128864',
      introduction: '祖庙建于北宋元丰年间（1078年-1085年），历经20多次重建和扩建，现存以万福台、灵应牌坊、锦香池、钟鼓楼、三门、前殿、正殿、庆真楼等明清建筑为主，具有典型的岭南建筑风格。',
      photo: '',
      video: 'https://youtu.be/ueW71rSmSAU',
      sound: '',
      owner: '',
      deleted: 'F',
      createUser: '',
      editUser: '',
      createDateTime: '',
      editDateTime: ''
  });

  Posts.insert({
      category: '',
      subCategory: '',
      title: '黃大仙廟',
      startTime: '',
      endTime: '',
      address: '香港九龍黃大仙竹園村二號',
      district: '九龍城區',
      city: '香港',
      xBaidu: '113.242597',
      yBaidu: '23.128864',
      introduction: '祖庙建于北宋元丰年间（1078年-1085年），历经20多次重建和扩建，现存以万福台、灵应牌坊、锦香池、钟鼓楼、三门、前殿、正殿、庆真楼等明清建筑为主，具有典型的岭南建筑风格。',
      photo: '',
      video: 'https://youtu.be/uJ0MMDI7HgY',
      sound: '',
      owner: '',
      deleted: 'F',
      createUser: '',
      editUser: '',
      createDateTime: '',
      editDateTime: ''
  });
}
